parameters:
    models: NCF
    rank: [100, 200]
    num_layers: [1]
    batch_size: [256]
    lambda: [0.001, 0.01, 0.1, 1.0, 10.0]
    topK: [5, 10, 15, 20, 50]
    learning_rate: [0.0001, 0.0005, 0.001]
    epoch: [100]
    metric: [R-Precision, NDCG, Precision, Recall, MAP]

